application: djangocomment
runtime: python
version: 1
api_version: 1

handlers:
- url: .*
  script: post.wsgi.app

libraries:
- name: PIL
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: 'post.settings'