application: djangocomment
runtime: python
version: 1
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.application


# libraries:
# - name: django
#   version: latest


# env_variables:
#   DJANGO_SETTINGS_MODULE: 'post.settings'