application: djangocomment
runtime: python
version: 1
api_version: 1

handlers:
- url: /patterns/.*
  script: /post/urls.py
- url: .*
  script: /post/urls.py
- url: .*
  script: /post/urls.py
- url: .*
  script: /post/urls.py

env_variables:
  DJANGO_SETTINGS_MODULE: 'post.settings'